version: '3'
services:
  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - 3306:3306
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 80:80

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db