version: '3'
services:
  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
#    image: gcr.io/tuhh-aic/aic_db
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
#    image: gcr.io/tuhh-aic/aic_frontend
    ports:
      - 80:80

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
#    image: gcr.io/tuhh-aic/aic_backend
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy